export const screenings = [
  {
    title: "Mulholland Drive",
    year: 2001,
    director: "David Lynch",
    format: "70mm",
    theater: "The Egyptian",
    neighborhood: "Hollywood",
    date: "2026-05-10",
    time: "9:30 PM",
    specialGuest: "Q&A with Laura Dern",
    poster: "/posters/mulholland-drive.jpg",
    tickets: "#",
  },
  {
    title: "The Third Man",
    year: 1949,
    director: "Carol Reed",
    format: "35mm",
    theater: "The New Beverly",
    neighborhood: "Fairfax",
    date: "2026-04-10",
    time: "7:00 PM",
    poster: "/posters/third-man.jpg",
    tickets: "#",
  },
  {
    title: "Paris, Texas",
    year: 1984,
    director: "Wim Wenders",
    format: "70mm",
    theater: "The Aero",
    neighborhood: "Santa Monica",
    date: "2026-04-11",
    time: "7:30 PM",
    poster: "/posters/paris-texas.jpg",
    tickets: "#",
  },

    {
    title: "Singin' in the Rain",
    year: 1952,
    director: "Gene Kelly, Stanley Donen",
    format: "4k restoration",
    theater: "The Academy Theater",
    neighborhood: "Santa Monica",
    date: "2026-04-12",
    time: "6:30 PM",
    poster: "/posters/rain.jpg",
    tickets: "#",
  },
];