export type Quote = {
  id: string;
  name: string;
  role: string;
  quote: string;
  era?: string;
  category?: "actor" | "actress" | "director" | "critic" | "producer" | "studio";
  source?: string;
};

export const quotes: Quote[] = [
  {
    id: "pauline-kael-1",
    name: "Pauline Kael",
    role: "Film Critic",
    category: "critic",
    quote: "Good movies make you care, make you believe in possibilities again.",
  },
  {
    id: "pauline-kael-2",
    name: "Pauline Kael",
    role: "Film Critic",
    category: "critic",
    quote: "Hollywood is the only place where you can die of encouragement.",
  },
  {
    id: "steven-spielberg-1",
    name: "Steven Spielberg",
    role: "Director",
    category: "director",
    quote: "Every time I go to a movie, it's magic, no matter what the movie's about.",
  },
  {
    id: "quentin-tarantino-1",
    name: "Quentin Tarantino",
    role: "Director",
    category: "director",
    quote: "As far as I'm concerned, digital projection and DCPs is the death of cinema as I know it.",
  },
  {
    id: "quentin-tarantino-2",
    name: "Quentin Tarantino",
    role: "Director",
    category: "director",
    quote: "I didn't go to film school. I went to films.",
  },
  {
    id: "guillermo-del-toro-1",
    name: "Guillermo del Toro",
    role: "Director",
    category: "director",
    quote: "Animation is cinema. Animation is not a genre.",
  },
  {
    id: "roger-ebert-1",
    name: "Roger Ebert",
    role: "Film Critic",
    category: "critic",
    quote: "For me, the movies are like a machine that generates empathy.",
  },
  {
    id: "roger-ebert-2",
    name: "Roger Ebert",
    role: "Film Critic",
    category: "critic",
    quote: "If it's a great movie, it lets you understand a little bit more about what it's like to be a different person.",
  },
  {
    id: "christopher-nolan-1",
    name: "Christopher Nolan",
    role: "Director",
    category: "director",
    quote: "Every film should have its own world, a logic and feel to it that expands beyond the exact image that the audience is seeing.",
  },
  {
    id: "wes-anderson-1",
    name: "Wes Anderson",
    role: "Director",
    category: "director",
    quote: "There are lots of very strong-minded, personal filmmakers and they will always do what they believe in.",
  },
  {
    id: "wes-anderson-2",
    name: "Wes Anderson",
    role: "Director",
    category: "director",
    quote: "I like to be dazzled in the movies.",
  },
  {
    id: "sidney-lumet-1",
    name: "Sidney Lumet",
    role: "Director",
    category: "director",
    quote: "It's an enormously, incredibly satisfying way to work.",
  },
  {
    id: "charlie-chaplin-1",
    name: "Charlie Chaplin",
    role: "Actor / Filmmaker",
    category: "actor",
    quote: "We think too much and feel too little.",
  },
  {
    id: "douglas-fairbanks-1",
    name: "Douglas Fairbanks",
    role: "Actor",
    category: "actor",
    quote: "The man that's out to do something has to keep in high gear all the time.",
  },
  {
    id: "clark-gable-1",
    name: "Clark Gable",
    role: "Actor",
    category: "actor",
    quote: "The only reason they come to see me is that I know that life is great and they know I know it.",
  },
  {
    id: "walt-disney-1",
    name: "Walt Disney",
    role: "Producer / Filmmaker",
    category: "producer",
    quote: "By nature I'm an experimenter.",
  },
  {
    id: "humphrey-bogart-1",
    name: "Humphrey Bogart",
    role: "Actor",
    category: "actor",
    quote: "Acting is experience with something sweet behind it.",
  },
  {
    id: "ingrid-bergman-1",
    name: "Ingrid Bergman",
    role: "Actress",
    category: "actress",
    quote: "The best way to keep young is to keep going.",
  },
  {
    id: "orson-welles-1",
    name: "Orson Welles",
    role: "Director / Actor",
    category: "director",
    quote: "A film is never really good unless the camera is an eye in the head of a poet.",
  },
  {
    id: "marlon-brando-1",
    name: "Marlon Brando",
    role: "Actor",
    category: "actor",
    quote: "The only thing an actor owes his public is not to bore them.",
  },
  {
    id: "marilyn-monroe-1",
    name: "Marilyn Monroe",
    role: "Actress",
    category: "actress",
    quote: "If I say I want to grow as an actress, they laugh.",
  },
  {
    id: "james-dean-1",
    name: "James Dean",
    role: "Actor",
    category: "actor",
    quote: "Being an actor is the loneliest thing in the world.",
  },
  {
    id: "sidney-poitier-1",
    name: "Sidney Poitier",
    role: "Actor",
    category: "actor",
    quote: "I did not go into the film business to be symbolized as someone else's vision of me.",
  },
  {
    id: "alfred-hitchcock-1",
    name: "Alfred Hitchcock",
    role: "Director",
    category: "director",
    quote: "Drama is life with the dull bits left out.",
  },
  {
    id: "george-lucas-1",
    name: "George Lucas",
    role: "Director",
    category: "director",
    quote: "A special effect is a tool, a means of telling a story.",
  },
  {
    id: "robert-de-niro-1",
    name: "Robert De Niro",
    role: "Actor",
    category: "actor",
    quote: "Movies are hard to make, and you have to work toward a common ethic and do your best.",
  },
  {
    id: "al-pacino-1",
    name: "Al Pacino",
    role: "Actor",
    category: "actor",
    quote: "The hardest thing about being famous is that people are always nice to you.",
  },
  {
    id: "tom-cruise-1",
    name: "Tom Cruise",
    role: "Actor",
    category: "actor",
    quote: "I don't care if you print something nasty about me, just make sure it's the truth.",
  },
  {
    id: "tom-hanks-1",
    name: "Tom Hanks",
    role: "Actor",
    category: "actor",
    quote: "The cinema has the power to make you not feel lonely, even when you are.",
  },
  {
    id: "greta-gerwig-1",
    name: "Greta Gerwig",
    role: "Director / Writer",
    category: "director",
    quote: "Film can capture a moment of spontaneous life that will never be captured again.",
  },
];
